name: rft-ft-cli-demo
description: Template to demonstrate reinforcement fine-tuning via CLI
model: o4-mini-2025-04-16
method:
  type: reinforcement
  reinforcement:
    hyperparameters:
      epochs: 3
      batch_size: 8
      learning_rate_multiplier: 1.0
      beta: 0.5
      compute_multiplier: 1.0
      reasoning_effort: high
    grader:
      type: string_check
      input: "{{sample.output_text}}"
      reference: "{{item.target}}"
      operation: eq
suffix: "rft-trained"
seed: 42
training_file: local:data/rft_training_set.jsonl
validation_file: local:data/rft_validation_set.jsonl
